Header:
    version: 157
ImportedPackages:
- "~res:/UI/Screens3/Common/VerticalScrollBar.yaml"
Prototypes:
-   class: "UIControl"
    name: "RightPanel"
    input: false
    components:
        Anchor:
            topAnchorEnabled: true
        LinearLayout: {}
        SizePolicy:
            horizontalPolicy: "PercentOfChildrenSum"
            verticalPolicy: "Formula"
            verticalFormula: "when parent == 0 -> childrenSum, min(parentRest, childrenSum)"
        UIDataParamsComponent:
            params:
            - ["string", "backgroundStyle", "\"grey-shark-90-bg\"", "\"grey-shark-90-bg\""]
            - ["control", "header", "null", "null"]
            - ["control", "content", "null", "null"]
            - ["control", "footer", "null", "null"]
    children:
    -   class: "UIControl"
        name: "Content"
        components:
            Background: {}
            ClipContent: {}
            LinearLayout:
                orientation: "TopDown"
            SizePolicy:
                horizontalPolicy: "FixedSize"
                horizontalValue: 348.000000
                verticalPolicy: "Formula"
                verticalFormula: "when parent == 0 -> childrenSum, min(parent, childrenSum)"
            StyleSheet:
                styles: "~res:/UI/Screens3/Color.style.yaml"
        children:
        -   class: "UIControl"
            name: "Background"
            size: [32.000000, 32.000000]
            input: false
            components:
                Background:
                    usePostProcessedSprite: true
                UIPostProcessTextureComponent0:
                    materialPath: "~res:/Materials.custom/2d.Textured.Blur.material"
                    needClearAlphaAfterRender: true
                    scale: 0.500000
                    useVirtualCoordinateSystem: true
                    minFilter: "Linear"
                    magFilter: "Linear"
                UIPostProcessTextureComponent1:
                    materialPath: "~res:/Materials.custom/2d.Textured.HBlur.material"
                    scale: 0.500000
                    useVirtualCoordinateSystem: true
                    minFilter: "Linear"
                    magFilter: "Linear"
                UIPostProcessTextureComponent2:
                    materialPath: "~res:/Materials.custom/2d.Textured.UpscaleClamp.material"
                    scale: 0.500000
                    useVirtualCoordinateSystem: true
                    minFilter: "Linear"
                    magFilter: "Linear"
                UIRoundedCornersComponent:
                    radius: "8"
                IgnoreLayout: {}
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfParent"
                StyleSheet:
                    styles: "~res:/UI/Screens3/Color.style.yaml"
        -   class: "UIControl"
            name: "Header"
            input: false
            components:
                LinearLayout:
                    padding: "20"
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfMaxChild"
                UIChildComponent0:
                    childType: "kControl"
                    condition: "not isNull(header)"
                    control: "header"
        -   class: "UIScrollView"
            name: "ContentArea"
            autoUpdate: true
            components:
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "Formula"
                    verticalFormula: "when parent == 0 -> maxChild, min(parentRest, maxChild)"
            children:
            -   class: "UIScrollViewContainer"
                name: "scrollContainerControl"
                components:
                    LinearLayout:
                        padding: "20"
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfChildrenSum"
                    UIChildComponent0:
                        childType: "kControl"
                        condition: "not isNull(content)"
                        control: "content"
            -   prototype: "VerticalScrollBar/VerticalScrollBar"
                name: "VerticalScrollBar"
                position: [348.000000, 0.000000]
                components:
                    Anchor:
                        enabled: true
                        rightAnchorEnabled: true
                        rightAnchor: 2.000000
                        topAnchorEnabled: true
                        topAnchor: 8.000000
                        bottomAnchorEnabled: true
                        bottomAnchor: 8.000000
                    IgnoreLayout: {}
                    ScrollBarDelegate:
                        delegate: ".."
        -   class: "UIControl"
            name: "Footer"
            input: false
            components:
                LinearLayout:
                    padding: "20"
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfMaxChild"
                UIChildComponent0:
                    childType: "kControl"
                    condition: "not isNull(footer)"
                    control: "footer"
