modules:
    "#vehicle:GB58_Cruiser_Mk_III":
        position: [4, 2]
    "#vehicleGun:_3pdr_gun_Hotchkiss":
        position: [1, 1]
    "#vehicleGun:_15mm_Machine_gun_BESA":
        position: [3, 2]
    "#vehicleGun:QF_6_pounder_8cwt_Mk_II":
        position: [3, 1]
    "#vehicleTurret:Turret_1_GB01_Medium_Mark_I":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB01_Medium_Mark_I":
        position: [2, 2]
    "#vehicleEngine:Vickers-Armstrong_MkII":
        position: [1, 3]
    "#vehicleChassis:Chassis_GB01_Medium_Mark_I_2":
        position: [1, 4]