modules:
    "#vehicle:GB09_Churchill_VII":
        position: [4, 2]
    "#vehicleGun:_2pdr_Gun_Mk_XT":
        position: [1, 1]
    "#vehicleGun:QF_6_pounder_Mk_V":
        position: [3, 1]
    "#vehicleGun:_75mm_Gun_Vickers_HV":
        position: [4, 1]
    "#vehicleTurret:Turret_1_GB08_Churchill_I":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB08_Churchill_I":
        position: [2, 1]
    "#vehicleEngine:Meadows_DAV":
        position: [1, 3]
    "#vehicleEngine:Vauxhall_Bedford_Twin_Six":
        position: [2, 3]
    "#vehicleChassis:Chassis_GB08_Churchill_I":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB08_Churchill_I_2":
        position: [2, 4]