modules:
    "#vehicle:T54E1":
        position: [4, 1]
    "#vehicle:A99_T92E1":
        position: [3, 3]
    "#vehicleGun:_90mm_Gun_T132E3":
        position: [1, 1]
    "#vehicleGun:_90mm_Gun_T132E4":
        position: [3, 1]
    "#vehicleGun:_152mm_Gun_Launcher_M81":
        position: [3, 2]
    "#vehicleTurret:Turret_1_A100_T49":
        position: [1, 2]
    "#vehicleTurret:Turret_2_A100_T49":
        position: [2, 2]
    "#vehicleEngine:Continental_AOS-895-3":
        position: [1, 3]
    "#vehicleEngine:Continental_AOSI-895-5":
        position: [2, 3]
    "#vehicleChassis:Chassis_A100_T49":
        position: [1, 4]
    "#vehicleChassis:Chassis_A100_T49_2":
        position: [2, 4]