modules:
    "#vehicle:T71":
        position: [5, 1]
    "#vehicleGun:_75mm_Gun_M6":
        position: [1, 1]
    "#vehicleGun:_76mm_Gun_T94":
        position: [2, 1]
    "#vehicleGun:_76mm_Gun_T91":
        position: [4, 1]
    "#vehicleGun:_76mm_Gun_T102":
        position: [4, 2]
    "#vehicleTurret:Turret_1_T37":
        position: [1, 2]
    "#vehicleTurret:Turret_2_T37":
        position: [3, 1]
    "#vehicleEngine:Continental_AOS-895-1":
        position: [1, 3]
    "#vehicleEngine:Continental_AOS-895-3":
        position: [2, 3]
    "#vehicleChassis:Chassis_T37":
        position: [1, 4]
    "#vehicleChassis:Chassis_T37_2":
        position: [2, 4]