modules:
    "#vehicle:M48A1":
        position: [3, 2]
    "#vehicleGun:_90mm_Gun_M36":
        position: [1, 1]
    "#vehicleGun:_90mm_Gun_T15E2M2":
        position: [2, 1]
    "#vehicleGun:_105mm_Gun_T5E1M2":
        position: [2, 2]
    "#vehicleTurret:Turret_1_M46_Patton":
        position: [1, 3]
    "#vehicleTurret:Turret_2_M46_Patton":
        position: [2, 3]
    "#vehicleEngine:Ford_GAN":
        position: [1, 4]
    "#vehicleEngine:Continental_AV-1790-1":
        position: [2, 4]
    "#vehicleEngine:Continental_AV-1790-1M2":
        position: [3, 4]
    "#vehicleChassis:Chassis_M46_Patton":
        position: [1, 5]
    "#vehicleChassis:Chassis_M46_Patton_2":
        position: [2, 5]