modules:
    "#vehicle:T20":
        position: [3, 2]
    "#vehicleGun:_76mm_Gun_M1A1":
        position: [1, 1]
    "#vehicleGun:_76mm_Gun_M1A2":
        position: [3, 1]
    "#vehicleTurret:D51074":
        position: [1, 2]
    "#vehicleTurret:D51080":
        position: [2, 1]
    "#vehicleEngine:Wright_Continental_R-975C1":
        position: [1, 3]
    "#vehicleEngine:Wright_Continental_R-975C4":
        position: [2, 3]
    "#vehicleEngine:Ford_GAA":
        position: [3, 3]
    "#vehicleChassis:NVSS_T66":
        position: [1, 4]
    "#vehicleChassis:NVSS_T80":
        position: [2, 4]