modules:
    "#vehicle:M46_Patton":
        position: [3, 2]
    "#vehicleGun:_76mm_Gun_M1A2":
        position: [1, 1]
    "#vehicleGun:_90mm_Gun_M3":
        position: [2, 1]
    "#vehicleGun:_90mm_Gun_T15E2M2":
        position: [3, 1]
    "#vehicleTurret:Turret_1_Pershing":
        position: [1, 2]
    "#vehicleTurret:Turret_2_Pershing":
        position: [2, 2]
    "#vehicleEngine:Ford_GAN":
        position: [1, 3]
    "#vehicleEngine:Continental_AV-1790-1":
        position: [2, 3]
    "#vehicleChassis:Pershingchassis1":
        position: [1, 4]
    "#vehicleChassis:Pershingchassis2":
        position: [2, 4]