modules:
    "#vehicle:M2_lt":
        position: [3, 2]
    "#vehicleGun:_37mm_Gun_M1916":
        position: [1, 1]
    "#vehicleGun:_20mm_Hispano_Suiza_Birgikt_gun":
        position: [3, 1]
    "#vehicleGun:_37mm_Browning_semiautomatic_gun":
        position: [3, 3]
    "#vehicleTurret:Cunningham_D1":
        position: [1, 2]
    "#vehicleTurret:Cunningham_D2":
        position: [2, 2]
    "#vehicleEngine:Cunningham_type_3":
        position: [1, 3]
    "#vehicleChassis:Cunningham_E2":
        position: [1, 4]