modules:
    "#vehicle:T28":
        position: [3, 2]
    "#vehicleGun:_90mm_AT_Gun_M3":
        position: [1, 1]
    "#vehicleGun:_90mm_AT_Gun_T15E2":
        position: [2, 1]
    "#vehicleGun:_105mm_AT_Gun_T5E1":
        position: [3, 1]
    "#vehicleEngine:Ford_GAN":
        position: [1, 2]
    "#vehicleEngine:Continental_AV-1790-1":
        position: [2, 2]
    "#vehicleChassis:Chassis_T25_AT":
        position: [1, 3]
    "#vehicleChassis:Chassis_T25_AT_2":
        position: [2, 3]