modules:
    "#vehicle:AMX_50B":
        position: [3, 1]
    "#vehicleGun:_100mm_SA_47Mod0":
        position: [1, 1]
    "#vehicleGun:_100mm_SA_47":
        position: [2, 1]
    "#vehicleGun:_120mm_D_1203_Mod1":
        position: [2, 2]
    "#vehicleTurret:Turret_1_AMX_50_120":
        position: [1, 2]
    "#vehicleEngine:Maybach_HL_295":
        position: [1, 3]
    "#vehicleEngine:Saurer":
        position: [2, 3]
    "#vehicleChassis:Chassis_AMX_50_120":
        position: [1, 4]
    "#vehicleChassis:Chassis_AMX_50_120_2":
        position: [2, 4]