modules:
    "#vehicle:AMX_13_75":
        position: [3, 2]
    "#vehicle:F126_AMX_13_M24":
        position: [3, 3]
    "#vehicleGun:_75mm_SA49":
        position: [1, 2]
    "#vehicleGun:_75mm_SA50":
        position: [2, 2]
    "#vehicleTurret:Turret_1_AMX_12t":
        position: [1, 3]
    "#vehicleEngine:AMX_B_270":
        position: [1, 4]
    "#vehicleEngine:MATHIS":
        position: [2, 4]
    "#vehicleChassis:Chassis_AMX_12t_1_prototype":
        position: [1, 5]
    "#vehicleChassis:Chassis_AMX_12t_2_prototype":
        position: [2, 5]