modules:
    "#vehicle:RenaultR35":
        position: [4, 2]
    "#vehicleGun:_37mm_APX_SA18":
        position: [1, 1]
    "#vehicleGun:_25mm_Canon_Raccourci_Mle.1934":
        position: [3, 1]
    "#vehicleGun:_13.2mm_Hotchkiss_mle._1930":
        position: [3, 2]
    "#vehicleTurret:Turret_1_RenaultFT":
        position: [1, 2]
    "#vehicleTurret:Turret_2_RenaultFT":
        position: [2, 2]
    "#vehicleEngine:Franklin":
        position: [1, 3]
    "#vehicleChassis:Chassis_RenaultFT2":
        position: [1, 4]