modules:
    "#vehicle:Ha_Go":
        position: [4, 1]
    "#vehicle:Chi_Ni":
        position: [4, 3]
    "#vehicleGun:_37mm_APX_SA18":
        position: [1, 1]
    "#vehicleGun:_37mm_Sogekiho":
        position: [3, 1]
    "#vehicleGun:_13.2mm_Type93":
        position: [3, 3]
    "#vehicleTurret:Turret_1_NC27":
        position: [1, 2]
    "#vehicleTurret:Turret_2_NC27":
        position: [2, 2]
    "#vehicleEngine:Mitsubishi":
        position: [1, 3]
    "#vehicleChassis:Chassis_NC27":
        position: [1, 4]