ExplosionWave: ##气浪
    TankExplosion: ##坦克爆炸
        waveSpeed: 150 ##气浪速度
        waveDamping: 0.005 ##气浪阻尼
        waveRadius: 100 ##气浪半径
        waveAmplitude: 1.5 ##气浪幅度 = (1 - 阻尼 / R)
        waveEffectDuration: 1.5 ##气浪持续时间
    GunShotImpactExplosion: ##火炮气浪
        waveSpeed: 75 ##气浪速度
        waveDamping: 0.005 ##气浪阻尼
        waveRadius: 30 ##气浪半径
        waveAmplitude: 0.5 ##气浪幅度
        waveEffectDuration: 1.5 ##气浪持续时间
    GunShotAuto: ##火炮气浪
        minCaliber: 0 ##最小口径
        maxCaliber: 30 ##最大口径
        waveSpeed: 85 ##气浪速度
        waveDamping: 0.035 ##气浪阻尼
        waveRadius: 35 ##气浪半径
        waveAmplitude: 0.5 ##气浪幅度
        waveEffectDuration: 1.25 ##气浪持续时间
    GunShotSmall:
        minCaliber: 31
        maxCaliber: 50
        waveSpeed: 100
        waveDamping: 0.03
        waveRadius: 40
        waveAmplitude: 0.75
        waveEffectDuration: 1.35
    GunShotMedium:
        minCaliber: 51
        maxCaliber: 77
        waveSpeed: 115
        waveDamping: 0.025
        waveRadius: 45
        waveAmplitude: 1.0
        waveEffectDuration: 1.45
    GunShotMain:
        minCaliber: 78
        maxCaliber: 100
        waveSpeed: 130
        waveDamping: 0.02
        waveRadius: 50
        waveAmplitude: 1.25
        waveEffectDuration: 1.55
    GunShotLarge:
        minCaliber: 101
        maxCaliber: 130
        waveSpeed: 145
        waveDamping: 0.015
        waveRadius: 55
        waveAmplitude: 1.5
        waveEffectDuration: 1.65
    GunShotHuge: ##火炮气浪
        minCaliber: 131 ##最小口径
        maxCaliber: 240 ##最大口径
        waveSpeed: 160 ##气浪速度
        waveDamping: 0.01 ##气浪阻尼
        waveRadius: 60 ##气浪半径
        waveAmplitude: 1.75 ##气浪幅度
        waveEffectDuration: 1.75 ##气浪持续时间
ExplosionWaveBushResponse: ## 植物对气浪的反应
    maxBushBoneAngle: 0.35 ## 小灌木最大弧度
    maxTreeBoneAngle: 0.045 ## 树干最大弧度
    maxFloraAmplitude: 0.85 ## 植物群摆动幅度
    bushPushDuration: 0.3 ## 小灌木第一次向前摆动持续时间
    bushTrailDuration: 2.0 ## 小灌木摆动持续时间
    floraPushDuration: 0.05 ## 植物群第一次向前摆动持续时间
    floraTrailDuration: 2.5 ## 植物群摆动持续时间
