keyedArchive:
    altShellAvgDamage:
        keyedArchive: {}
    altShellAvgPiercingPower:
        keyedArchive: {}
    baseShellAvgDamage:
        keyedArchive: {}
    baseShellAvgPiercingPower:
        keyedArchive: {}
    premShellAvgDamage:
        keyedArchive: {}
    premShellAvgPiercingPower:
        keyedArchive: {}
    avgSpeed:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'KILOMETER_PER_HOUR'
    maxBackSpeed:
        keyedArchive:
            units:
                string: 'KILOMETER_PER_HOUR'
    maxFrontSpeed:
        keyedArchive:
            units:
                string: 'KILOMETER_PER_HOUR'
    weight:
        keyedArchive:
            biggerIsBetter:
                bool: false
            digits:
                int32: 3
            units:
                string: 'TON'
    chassiMaxLoad:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'TON'
    chassiRotationSpeed:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'DEGREE_PER_SECOND'
    circularVisionRadius:
        keyedArchive:
            digits:
                int32: 3
    engineFireStartingChance:
        keyedArchive:
            biggerIsBetter:
                bool: false
            units:
                string: 'PERCENT'
    enginePower:
        keyedArchive:
            digits:
                int32: 1
            units:
                string: 'HORSE_POWER'
    gunAimingTime:
        keyedArchive:
            biggerIsBetter:
                bool: false
            digits:
                int32: 3
    gunBurstCapacity:
        keyedArchive: {}
    gunBurstShellCount:
        keyedArchive: {}
    gunClipBurstCount:
        keyedArchive: {}
    gunClipBurstReloadTime:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunClipCapacity:
        keyedArchive: {}
    gunClipShellCount:
        keyedArchive: {}
    gunClipReloadTime:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunClipShellReloadTime:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false 
    timeBetweenPumpShots:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunCommonDamagePerMin:
        keyedArchive:
            digits:
                int32: 3
    gunCommonReloadTime:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunDamageForComparing:
        keyedArchive: {}
    gunPitchLimits:
        keyedArchive:
            units:
                string: 'DEGREE'
    gunPitchMaxLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    gunPitchMinLimit:
        keyedArchive:
            biggerIsBetter:
                bool: false
            units:
                string: 'DEGREE'
    gunPitchUpLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    gunPitchDownLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    gunShellReloadTime:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunShotDispersionRadius:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    gunShotsPerMinute:
        keyedArchive:
            digits:
                int32: 3
    hasTurret:
        keyedArchive: {}
    pumpGunMode:
        keyedArchive: {}
    reloadingShellTime0:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    reloadingShellTime1:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    reloadingShellTime2:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    reloadingShellTime3:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    reloadingShellTime4:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    reloadingShellTime5:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    healthBurnPerSec:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
    hullAverageThickness:
        keyedArchive:
            digits:
                int32: 3
    maxHealth:
        keyedArchive: {}
    stillInvisibility:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    movingInvisibility:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    shotInvisibility:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    primaryArmorFront:
        keyedArchive: {}
    primaryArmorSide:
        keyedArchive: {}
    primaryArmorRear:
        keyedArchive: {}
    turretArmorFront:
        keyedArchive: {}
    turretArmorSide:
        keyedArchive: {}
    turretArmorRear:
        keyedArchive: {}
    terrainPermeabilityFirm:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    terrainPermeabilityMedium:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    terrainPermeabilitySoft:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'PERCENT'
    thrustToWeightRatio:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'HORSE_POWER_PER_TON'
    turretRotationSpeed:
        keyedArchive:
            digits:
                int32: 3
            units:
                string: 'DEGREE_PER_SECOND'
    turretYawLimits:
        keyedArchive:
            units:
                string: 'DEGREE'
    turretYawMaxLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    turretYawMinLimit:
        keyedArchive:
            biggerIsBetter:
                bool: false
            units:
                string: 'DEGREE'
    turretYawLeftLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    turretYawRightLimit:
        keyedArchive:
            units:
                string: 'DEGREE'
    gunShotDispersionFactors:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
            units:
                string: 'GUN_SHOT_DISPERSION_COEFFICIENT'
    gunShotDispersionFactorsTurretRotation:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
            units:
                string: 'GUN_SHOT_DISPERSION_COEFFICIENT'
    gunShotDispersionFactorsAfterShot:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
            units:
                string: 'GUN_SHOT_DISPERSION_COEFFICIENT'
    gunShotDispersionFactorsWhileGunDamaged:
        keyedArchive:
            digits:
                int32: 3
            biggerIsBetter:
                bool: false
            units:
                string: 'GUN_SHOT_DISPERSION_COEFFICIENT'
