modules:
    "#vehicle:E50_Ausf_M":
        position: [4, 1]
    "#vehicleGun:_88mm_KwK_43_L71":
        position: [1, 1]
    "#vehicleGun:_88mm_KwK_L100":
        position: [2, 1]
    "#vehicleGun:_105mm_KwK45_L52_ausf_B":
        position: [3, 1]
    "#vehicleTurret:Turret_1_E-50":
        position: [1, 2]
    "#vehicleTurret:Turret_2_E-50":
        position: [2, 2]
    "#vehicleEngine:Maybach_HL_230_TRM_P30":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_234_TRM_P30":
        position: [2, 3]
    "#vehicleChassis:Chassis_E-50":
        position: [1, 4]
    "#vehicleChassis:Chassis_E-50_2":
        position: [2, 4]