modules:
    "#vehicle:JagdPantherII":
        position: [4, 2]
    "#vehicle:Ferdinand":
        position: [4, 3]
    "#vehicleGun:_75mm_StuK42_L70":
        position: [1, 1]
    "#vehicleGun:_88mm_PaK_36_L56":
        position: [2, 1]
    "#vehicleGun:_88mm_PaK_43_L71":
        position: [3, 1]
    "#vehicleGun:_105mm_K18_L52":
        position: [4, 1]
    "#vehicleEngine:Maybach_HL_210_TRM_P30":
        position: [1, 2]
    "#vehicleEngine:Maybach_HL_230_TRM_P30":
        position: [2, 2]
    "#vehicleChassis:JgPzV_Standardketten":
        position: [1, 3]
    "#vehicleChassis:JgPzV_Vetstaerktketten":
        position: [2, 3]
