modules:
    "#vehicle:Sturer_Emil":
        position: [4, 1]
    "#vehicle:JagdPanther":
        position: [3, 2]
    "#vehicleGun:_75mm_StuK42_L70":
        position: [1, 1]
    "#vehicleGun:_88mm_PaK_36_L56":
        position: [2, 1]
    "#vehicleGun:_88mm_PaK_43_L71":
        position: [3, 1]
    "#vehicleEngine:Maybach_HL_108_TR_R":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_120_TRM_112_R":
        position: [2, 3]
    "#vehicleEngine:Maybach_HL_120_TRM_R":
        position: [3, 3]
    "#vehicleChassis:Chassis_Nashorn":
        position: [1, 4]
    "#vehicleChassis:Chassis_Nashorn_2":
        position: [2, 4]