modules:
    "#vehicle:E-50":
        position: [3, 2]
    "#vehicleGun:_75mm_KwK45_L100":
        position: [1, 1]
    "#vehicleGun:_88mm_KwK_36_L56":
        position: [3, 1]
    "#vehicleGun:_88mm_KwK_43_L71":
        position: [3, 3]
    "#vehicleTurret:Turret_1_Panther_II":
        position: [1, 2]
    "#vehicleTurret:Turret_2_Panther_II":
        position: [2, 1]
    "#vehicleEngine:Maybach_HL_210_TRM_P30":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_230_TRM_P30V2":
        position: [2, 3]
    "#vehicleChassis:Chassis_Panther_II":
        position: [1, 4]
    "#vehicleChassis:Chassis_Panther_II_2":
        position: [2, 4]