modules:
    "#vehicle:Ferdinand":
        position: [3, 5]
    "#vehicle:G115_VK10001P":
        position: [3, 3]
    "#vehicle:VK4502A":
        position: [2, 2]
    "#vehicleGun:_88mm_KwK_36_L56":
        position: [1, 1]
    "#vehicleGun:_88mm_KwK_43_L71":
        position: [2, 1]
    "#vehicleTurret:Turret_1_PzVI_Tiger_P":
        position: [1, 3]
    "#vehicleTurret:Turret_2_PzVI_Tiger_P":
        position: [2, 3]
    "#vehicleEngine:Porsche_Typ_100_1":
        position: [2, 4]
    "#vehicleEngine:Porsche_Typ_100_1A":
        position: [1, 4]
    "#vehicleEngine:Porsche_Typ_100_3":
        position: [3, 4]
    "#vehicleChassis:Chassis_PzVI_Tiger_P":
        position: [1, 5]
    "#vehicleChassis:Chassis_PzVI_Tiger_P_2":
        position: [2, 5]