modules:
    "#vehicle:VK3002DB":
        position: [3, 2]
    "#vehicle:PzV":
        position: [4, 1]
    "#vehicleGun:_75mm_KwK_40_L48":
        position: [1, 1]
    "#vehicleGun:_75mm_KwK_L70":
        position: [3, 1]
    "#vehicleTurret:Turret_1_VK3002DB_V1":
        position: [1, 2]
    "#vehicleTurret:Turret_2_VK3002DB_V1":
        position: [2, 2]
    "#vehicleEngine:MB-503":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_210_TRM_P30":
        position: [2, 3]
    "#vehicleEngine:Maybach_HL_230_TRM_P30v3":
        position: [3, 3]
    "#vehicleChassis:Chassis_VK3002DB_V1":
        position: [1, 4]
    "#vehicleChassis:Chassis_VK3002DB_V1_2":
        position: [2, 4]