types:
-   'param'
-   'subsection'
-   'subparam'
-   'ammo_subparam'
-   'table' # maximum count of columns - 3
-   'row'
-   'pairparam'
-   'baseparam'
mainSections: ['protectability', 'gun', 'mobility']
sections:
-   section: 'base'
    content:
    -   base: 'maxHealth'
        baseparam: 'maxHealth'
    -   base: 'damage'
        baseparam: 'baseShellAvgDamage'
    -   base: 'firingRate'
        baseparam: 'gunShotsPerMinute'
    -   base: 'penetration'
        baseparam: 'baseShellAvgPiercingPower'
    -   base: 'armor'
        baseparam: 'hullAverageThickness'
    -   base: 'speed'
        baseparam: 'avgSpeed'
    -   base: 'rotation'
        baseparam: 'chassiRotationSpeed'
-   section: 'rawbase'
    content:
    -   base: 'maxHealth'
        baseparam: 'maxHealth'
    -   base: 'damage'
        baseparam: 'gunDamageForComparing'
    -   base: 'firingRate'
        baseparam: 'gunShotsPerMinute'
    -   base: 'penetration'
        baseparam: 'baseShellAvgPiercingPower'
    -   base: 'armor'
        baseparam: 'hullAverageThickness'
    -   base: 'speed'
        baseparam: 'avgSpeed'
    -   base: 'rotation'
        baseparam: 'chassiRotationSpeed'
-   section: 'protectability'
    content:
    -   param: 'maxHealth'
    -   table: 'armor'
        columns: ['turretArmor', 'hullArmor']
        columnsPresented: ['hasTurret', '']
        content:
        -   row: "frontArmor"
            content:
            -   param: 'turretArmorFront'
            -   param: 'primaryArmorFront'
        -   row: 'sideArmor'
            content:
            -   param: 'turretArmorSide'
            -   param: 'primaryArmorSide'
        -   row: "rearArmor"
            content:
            -   param: 'turretArmorRear'
            -   param: 'primaryArmorRear'
    -   param: 'engineFireStartingChance'
    -   param: 'circularVisionRadius'
    -   subsection: 'invisibility'
        content:
        -   subparam: 'stillInvisibility'
        -   subparam: 'movingInvisibility'
        -   subparam: 'shotInvisibility'
-   section: 'gun'
    content:    
    -   param: 'gunCommonDamagePerMin'
    -   param: 'gunShellReloadTime'
    -   param: 'gunClipReloadTime'
    -   param: 'gunClipShellReloadTime'
    -   param: 'timeBetweenPumpShots'
    -   param: 'gunClipBurstReloadTime'
    -   subsection: 'gunClipShellPumpReloadTime'
        presented: 'pumpGunMode'
        content:
        -   subparam: 'reloadingShellTime0'
        -   subparam: 'reloadingShellTime1'
        -   subparam: 'reloadingShellTime2'
        -   subparam: 'reloadingShellTime3'
        -   subparam: 'reloadingShellTime4'
        -   subparam: 'reloadingShellTime5'
    -   param: 'gunClipShellCount'
    -   param: 'gunClipBurstCount'
    -   param: 'gunBurstShellCount'
    -   subsection: 'shellAvgPiercing'
        content:
        -   ammo_subparam: 'baseShellAvgPiercingPower'
        -   ammo_subparam: 'premShellAvgPiercingPower'
        -   ammo_subparam: 'altShellAvgPiercingPower'
    -   subsection: 'shellAvgDamage'
        content:
        -   ammo_subparam: 'baseShellAvgDamage'
        -   ammo_subparam: 'premShellAvgDamage'
        -   ammo_subparam: 'altShellAvgDamage'
    -   param: 'gunAimingTime'
    -   param: 'gunShotDispersionRadius'
    -   subsection: 'gunShotDispersionFactors'
        content:
        -   subparam: 'gunShotDispersionFactorsTurretRotation'
        -   subparam: 'gunShotDispersionFactorsAfterShot'
        -   subparam: 'gunShotDispersionFactorsWhileGunDamaged'
    -   subsection: 'gunPitchLimits'
        content:
        -   subparam: 'gunPitchUpLimit'
        -   subparam: 'gunPitchDownLimit'
    -   subsection: 'turretYawLimits'
        content:
        -   subparam: 'turretYawLeftLimit'
        -   subparam: 'turretYawRightLimit'
-   section: 'mobility'
    content:
    -   subsection: 'maxSpeed'
        content:
        -   subparam: 'maxFrontSpeed'
        -   subparam: 'maxBackSpeed'
    -   param: 'avgSpeed'
    -   param: 'thrustToWeightRatio'
    -   param: 'weight'
    -   param: 'turretRotationSpeed'
    -   param: 'chassiRotationSpeed'
    -   subsection: 'terrainPermeability'
        content:
        -   subparam: 'terrainPermeabilityFirm'
        -   subparam: 'terrainPermeabilityMedium'
        -   subparam: 'terrainPermeabilitySoft'
    -   param: 'enginePower'
-   section: 'vehicleChassis'
    content:
    -   param: 'weight'
    -   param: 'chassiRotationSpeed'
    -   param: 'gunAimingTime'
    -   subsection: 'terrainPermeability'
        content:
        -   subparam: 'terrainPermeabilityFirm'
        -   subparam: 'terrainPermeabilityMedium'
        -   subparam: 'terrainPermeabilitySoft'
-   section: 'vehicleEngine'
    content:
    -   param: 'weight'
    -   param: 'enginePower'
    -   param: 'engineFireStartingChance'
    -   subsection: 'maxSpeed'
        content:
        -   subparam: 'maxFrontSpeed'
        -   subparam: 'maxBackSpeed'
    -   param: 'avgSpeed'
    -   param: 'thrustToWeightRatio'
    -   param: 'chassiRotationSpeed'
-   section: 'vehicleTurret'
    content:
    -   param: 'weight'
    -   param: 'maxHealth'
    -   table: 'armor'
        columns: ['turretArmor']
        content:
        -   row: 'frontArmor'
            content:
            -   param: 'turretArmorFront'
        -   row: 'sideArmor'
            content:
            -   param: 'turretArmorSide'
        -   row: 'rearArmor'
            content:
            -   param: 'turretArmorRear'
    -   param: 'turretRotationSpeed'
    -   subsection: 'turretYawLimits'
        content:
        -   subparam: 'turretYawLeftLimit'
        -   subparam: 'turretYawRightLimit'
    -   param: 'circularVisionRadius'
    -   subsection: 'gunPitchLimits'
        content:
        -   subparam: 'gunPitchUpLimit'
        -   subparam: 'gunPitchDownLimit'
-   section: 'vehicleGun'
    content:
    -   param: 'weight'
    -   param: 'gunAimingTime'
    -   param: 'gunShotDispersionRadius'
    -   subsection: 'gunShotDispersionFactors'
        content:
        -   subparam: 'gunShotDispersionFactorsTurretRotation'
        -   subparam: 'gunShotDispersionFactorsAfterShot'
        -   subparam: 'gunShotDispersionFactorsWhileGunDamaged'
    -   param: 'gunCommonDamagePerMin'
    -   param: 'gunShellReloadTime'
    -   param: 'gunClipReloadTime'
    -   param: 'gunClipShellReloadTime'
    -   param: 'timeBetweenPumpShots'
    -   param: 'gunClipBurstReloadTime'
    -   subsection: 'gunClipShellPumpReloadTime'
        presented: 'pumpGunMode'
        content:
        -   subparam: 'reloadingShellTime0'
        -   subparam: 'reloadingShellTime1'
        -   subparam: 'reloadingShellTime2'
        -   subparam: 'reloadingShellTime3'
        -   subparam: 'reloadingShellTime4'
        -   subparam: 'reloadingShellTime5'
    -   param: 'gunClipShellCount'
    -   param: 'gunClipBurstCount'
    -   param: 'gunBurstShellCount' 
    -   subsection: 'shellAvgPiercing'
        content:
        -   ammo_subparam: 'baseShellAvgPiercingPower'
        -   ammo_subparam: 'premShellAvgPiercingPower'
        -   ammo_subparam: 'altShellAvgPiercingPower'
    -   subsection: 'shellAvgDamage'
        content:
        -   ammo_subparam: 'baseShellAvgDamage'
        -   ammo_subparam: 'premShellAvgDamage'
        -   ammo_subparam: 'altShellAvgDamage'
    -   subsection: 'gunPitchLimits'
        content:
        -   subparam: 'gunPitchUpLimit'
        -   subparam: 'gunPitchDownLimit'
    -   subsection: 'invisibility'
        content:
        -   subparam: 'shotInvisibility'
-   section: 'crew'
    content:
    -   param: 'gunShotsPerMinute'
    -   param: 'circularVisionRadius'
    -   param: 'gunAimingTime'
    -   param: 'gunShotDispersionRadius'
    -   subsection: 'gunShotDispersionFactors'
        content:
        -   subparam: 'gunShotDispersionFactorsTurretRotation'
        -   subparam: 'gunShotDispersionFactorsAfterShot'
        -   subparam: 'gunShotDispersionFactorswhileGunDamaged'
    -   param: 'turretRotationSpeed'
    -   param: 'chassiRotationSpeed'
    -   subsection: 'terrainPermeability'
        content:
        -   subparam: 'terrainPermeabilityFirm'
        -   subparam: 'terrainPermeabilityMedium'
        -   subparam: 'terrainPermeabilitySoft'
