modules:
    "#vehicle:AMX_50_100":
        position: [3, 2]
    "#vehicleGun:_90mm_F3":
        position: [1, 1]
    "#vehicleGun:_105mm_canon_13TR":
        position: [2, 1]
    "#vehicleGun:_90mm_canon_DCA_45":
        position: [3, 1]
    "#vehicleTurret:Turret_1_AMX_M4_1945":
        position: [1, 2]
    "#vehicleTurret:Turret_2_AMX_M4_1945":
        position: [2, 2]
    "#vehicleEngine:Maybach_HL_230":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_230P45":
        position: [2, 3]
    "#vehicleEngine:Maybach_HL_295":
        position: [3, 3]
    "#vehicleChassis:Chassis_AMX_M4_1945":
        position: [1, 4]
    "#vehicleChassis:Chassis_AMX_M4_1945_2":
        position: [2, 4]