modules:
    "#vehicle:AMX_AC_Mle1948":
        position: [2, 2]
    "#vehicleGun:_90mm_canon_DCA_30_CA":
        position: [1, 1]
    "#vehicleGun:_90mm_canon_DCA_45_AC":
        position: [2, 1]
    "#vehicleGun:_100mm_SA_47_AC":
        position: [3, 1]
    "#vehicleEngine:Maybach_HL_230K":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_230P45":
        position: [2, 3]
    "#vehicleEngine:Maybach_HL_295K":
        position: [3, 3]
    "#vehicleChassis:Chassis_AMX_AC_Mle1946":
        position: [1, 4]
    "#vehicleChassis:Chassis_AMX_AC_Mle1946_2":
        position: [2, 4]