modules:
    "#vehicle:AMX_M4_1945":
        position: [3, 1]
    "#vehicleTurret:Turret_1_ARL_44":
        position: [1, 3]
    "#vehicleTurret:Turret_2_ARL_44":
        position: [2, 2]
    "#vehicleGun:_90mm_canon_DCA_30":
        position: [1, 2]
    "#vehicleGun:_90mm_F3":
        position: [3, 2]
    "#vehicleGun:_90mm_canon_DCA_45F":
        position: [4, 2]
    "#vehicleGun:_105mm_canon_13TR_ARL":
        position: [4, 3]
    "#vehicleEngine:Maybach_HL_230":
        position: [1, 4]
    "#vehicleEngine:Maybach_HL_230P45":
        position: [2, 4]
    "#vehicleChassis:Chassis_ARL_44":
        position: [1, 5]
    "#vehicleChassis:Chassis_ARL_44_2":
        position: [2, 5]