modules:
    "#vehicle:AMX_AC_Mle1946":
        position: [3, 2]
    "#vehicleGun:_75mm_Long_44_AC":
        position: [1, 1]
    "#vehicleGun:_90mm_canon_DCA_30_CA":
        position: [2, 1]
    "#vehicleGun:_105mm_AC_mle_1930S":
        position: [3, 1]
    "#vehicleEngine:Renault_T12":
        position: [1, 2]
    "#vehicleEngine:Renault_T14":
        position: [2, 2]
    "#vehicleChassis:Chassis_ARL_V39":
        position: [1, 3]
    "#vehicleChassis:Chassis_ARL_V39_2":
        position: [2, 3]