#一级
#LT
"european:F01_Vickers_MkF":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"germany:PzII":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"china:Ch07_Vickers_MkE_Type_BT26":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"japan:Ha_Go":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"uk:GB69_Cruiser_Mk_II":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"usa:M2_lt":
- other:Oth10_WarDuck
- uk:GB_Mark_I
"ussr:T-26":
- other:Oth10_WarDuck
- uk:GB_Mark_I
#MT
"france:RenaultR35":
- other:Oth10_WarDuck
- uk:GB_Mark_I
#二级
#LT
"european:Pl07_14TP":
- japan:Ke_Ni_B
"usa:M5_Stuart":
- japan:Ke_Ni_B
"ussr:BT-7":
- japan:Ke_Ni_B
#MT
"germany:PzIII":
- japan:Ke_Ni_B
"china:Ch08_Type97_Chi_Ha":
- japan:Ke_Ni_B
"japan:Chi_Ha":
- japan:Ke_Ni_B
"uk:GB59_Cruiser_Mk_IV":
- japan:Ke_Ni_B
#四级
#LT
"china:Ch09_M5":
- usa:A77_T6M
"ussr:A-20":
- usa:A77_T6M
"european:S04_Lago-I":
- usa:A77_T6M
"germany:Pz_IV_AusfD":
- usa:A77_T6M
"japan:Chi_He":
- usa:A77_T6M
"usa:M7_med":
- usa:A77_T6M
#五级
#LT
"france:ELC_AMX":
- other:Oth17_BDT-5A
- other:Oth29_A15HW
"germany:VK1602":
- other:Oth17_BDT-5A
- other:Oth29_A15HW
"uk:GB20_Crusader":
- other:Oth17_BDT-5A
- other:Oth29_A15HW
#MT
"european:S02_StrvM42":
- other:Oth26_StrvM42HW
"european:Pl17_DS_PZlnz":
- other:Oth15_RustCrab
- other:Oth26_StrvM42HW
"germany:PzIV":
- other:Oth15_RustCrab
- other:Oth26_StrvM42HW
"china:Ch21_T34":
- other:Oth26_StrvM42HW
"japan:Chi_Nu":
- other:Oth15_RustCrab
- other:Oth26_StrvM42HW
"usa:M4_Sherman":
- other:Oth26_StrvM42HW
"ussr:T-34":
- other:Oth15_RustCrab
- other:Oth26_StrvM42HW
#HT
"france:BDR_G1B":
- other:Oth35_PanzerMejai
"japan:J30_Mitsu_108":
- other:Oth35_PanzerMejai
"uk:GB08_Churchill_I":
- other:Oth35_PanzerMejai
"usa:T1_hvy":
- other:Oth35_PanzerMejai
"ussr:KV1":
- other:Oth35_PanzerMejai
#TD
"european:It15_Semovente_M41":
- other:Oth24_StuH_42HW
"france:S_35CA":
- other:Oth24_StuH_42HW
"germany:StuGIII":
- other:Oth24_StuH_42HW
"uk:GB73_AT2":
- other:Oth24_StuH_42HW
"usa:M10_Wolverine":
- other:Oth24_StuH_42HW
"ussr:SU-85":
- other:Oth24_StuH_42HW
#六级
#LT
"france:AMX_12t":
- other:Oth27_M24_AMX
- other:Oth33_Blizzard_BP
"germany:VK2801":
- other:Oth27_M24_AMX
- other:Oth33_Blizzard_BP
"china:Ch15_59_16":
- other:Oth27_M24_AMX
- other:Oth33_Blizzard_BP
"usa:A94_T37":
- other:Oth27_M24_AMX
- other:Oth33_Blizzard_BP
"usa:M24_Chaffee":
- other:Oth27_M24_AMX
- other:Oth33_Blizzard_BP
"ussr:MT25":
- other:Oth27_M24_AMX
#MT
"european:S07_Strv_74":
- other:Strv_74A2
- other:Oth18_BDT-5B
"european:It10_P43_bis":
- other:Strv_74A2
- other:Oth18_BDT-5B
"european:Cz08_T-25":
- other:Strv_74A2
- other:Oth18_BDT-5B
"european:Pl18_BUGI":
- other:Strv_74A2
- other:Oth18_BDT-5B
"germany:VK3001P":
- other:Strv_74A2
- other:Oth18_BDT-5B
"germany:VK3002DB_V1":
- other:Strv_74A2
- other:Oth18_BDT-5B
"china:Ch20_Type58":
- other:Strv_74A2
- other:Oth18_BDT-5B
"japan:Chi_To":
- other:Strv_74A2
- other:Oth18_BDT-5B
"uk:GB19_Sherman_Firefly":
- other:Strv_74A2
- other:Oth18_BDT-5B
"uk:GB21_Cromwell":
- other:Strv_74A2
- other:Oth18_BDT-5B
"usa:M4A3E8_Sherman":
- other:Strv_74A2
- other:Oth18_BDT-5B
"ussr:T-34-85":
- other:Strv_74A2
- other:Oth18_BDT-5B
#HT
"european:Cz29_Skoda_P-JS":
- other:Oth31_T150BP
"european:Pl10_40TP_Habicha":
- other:Oth31_T150BP
"france:ARL_44":
- other:Oth31_T150BP
"germany:VK3601H":
- other:Oth31_T150BP
"japan:J29_Ju_Nu":
- other:Oth31_T150BP
"uk:GB09_Churchill_VII":
- other:Oth31_T150BP
"usa:M6":
- other:Oth31_T150BP
"ussr:KV-1s":
- other:Oth31_T150BP
"ussr:KV2":
- other:Oth31_T150BP
#七级
#LT
"france:AMX_13_75":
- other:Oth50_STT
- other:Oth20_M4FL10
"germany:G113_SP_I_C":
- other:Oth19_BDT-5C
- other:Oth50_STT
"china:Ch16_WZ_131":
- other:Oth19_BDT-5C
- other:Oth50_STT
"usa:T71":
- other:Oth20_M4FL10
- other:Oth50_STT
"usa:M41_Bulldog":
- other:Oth20_M4FL10
- other:Oth50_STT
"ussr:R107_LTB":
- other:Oth19_BDT-5C
- other:AMX_dracula
"ussr:R131_LTG":
- other:Oth36_Indien_Panzer_S1
- other:Oth50_STT
#MT
"european:S13_Leo":
- other:AMX_dracula
- other:Oth72_Hazard_I
"european:It09_P43_ter":
- other:AMX_dracula
- other:Oth19_BDT-5C
"european:Cz05_T34-100":
- other:AMX_dracula
- other:Oth72_Hazard_I
"european:Pl20_CS_44":
- other:AMX_dracula
- other:Oth39_T20_S2
"france:F126_AMX_13_M24":
- other:AMX_dracula
- other:Oth36_Indien_Panzer_S1
"germany:PzV":
- other:AMX_dracula
- other:Oth36_Indien_Panzer_S1
"germany:VK3002DB":
- other:Oth49_TM_04_NT
- other:Sega_Edelweiss
"china:Ch04_T34_1":
- other:Oth12_Sega_Hafen
- other:Oth19_BDT-5C
"japan:Chi_Ri":
- other:Oth12_Sega_Hafen
- other:Oth20_M4FL10
"uk:GB22_Comet":
- other:Oth39_T20_S2
- other:Oth72_Hazard_I
"usa:T20":
- other:Oth49_TM_04_NT
- other:Sega_Edelweiss
"ussr:T-43":
- other:Oth19_BDT-5C
- other:Oth49_TM_04_NT
#HT
"european:It116_Carro_d_assalto_P88":
- other:Oth16_KV_TG
- other:Oth66_E100ANN_S4
"european:Cz19_Vz_44_1":
- other:Oth34_PanzerMummy
- other:Sega_Nameless
"european:Pl11_45TP_Habicha":
- other:Oth34_PanzerMummy
- other:Oth42_ForestWitch_HW23
"france:AMX_M4_1945":
- other:Oth25_HWT20_FalconFire
- other:Oth70_Lightbringer
"germany:PzVI_Tiger_P":
- other:Oth09_WH_Predator
- other:Oth14_MdM_AshKnight
"germany:PzVI":
- other:Oth53_Rammer
- other:Oth66_E100ANN_S4
"china:Ch51_BZ_58": 
- other:Oth14_MdM_AshKnight
- other:Oth16_KV_TG
"china:Ch10_IS2":
- other:Oth22_Sega_Vulcan
- other:Oth23_Werewolf
"japan:J28_Ju_To":
- other:Oth23_Werewolf
- other:Oth53_Rammer
"uk:GB10_Black_Prince":
- other:Oth25_HWT20_FalconFire
- other:Oth66_E100ANN_S4
"usa:T29":
- other:Oth14_MdM_AshKnight
- other:Oth70_Lightbringer
"usa:M-7-Y":
- other:Oth28_Sturmfeur_HW
- other:Oth53_Rammer
"ussr:IS":
- other:Oth06_Sega_Lupus
- other:Oth09_WH_Predator
"ussr:KV-3":
- other:Oth23_Werewolf
- other:Oth28_Sturmfeur_HW
#TD
"european:It17_Semovente_mod_56":
- other:Van_Helsing
- other:WZ-135G_FT
"france:AMX_AC_Mle1946":
- other:Oth08_WH_Vindicator
"germany:Sturer_Emil":
- other:Van_Helsing
- other:Oth08_WH_Vindicator
"germany:JagdPanther":
- other:Oth08_WH_Vindicator
"china:Ch35_T-34-2G_FT":
- other:Van_Helsing
- other:Oth08_WH_Vindicator
"japan:J23_Chi_To_SPG":
- other:Van_Helsing
- other:Oth46_Charioteer_S3
"uk:GB75_AT7":
- other:Van_Helsing
- other:WZ-135G_FT
"uk:GB41_Challenger":
- other:Oth46_Charioteer_S3
- other:WZ-135G_FT
"usa:T25_2":
- other:Van_Helsing
- other:Oth46_Charioteer_S3
"usa:T25_AT":
- other:Oth08_WH_Vindicator
- other:WZ-135G_FT
"ussr:SU-152":
- other:Van_Helsing
- other:WZ-135G_FT
"ussr:SU100M1":
- other:WZ-135G_FT
#八级
#LT
"france:AMX_13_90":
- other:Oth47_AMX_13_90_S3
"germany:G103_RU_251":
- other:Oth47_AMX_13_90_S3
"china:Ch17_WZ131_1_WZ132":
- other:Oth47_AMX_13_90_S3
"uk:GB_FV301":
- other:Oth47_AMX_13_90_S3
"usa:A100_T49":
- other:Oth47_AMX_13_90_S3
"ussr:R109_T54S":
- other:Oth47_AMX_13_90_S3
#MT
"european:It14_P44_Pantera":
- other:Oth30_T54MS
- other:Oth40_TVP_46_S2
"european:Cz07_TVP_46":
- other:Akawara
- other:Oth40_TVP_46_S2
"european:Pl23_CS_53":
- other:Akawara
- other:Oth51_FD_24
"france:F123_ERAC_105_Proto":
- other:Akawara
- other:Oth37_T26_E4_SuperPershing_S1
"germany:Panther_II":
- other:Akawara
- other:Oth37_T26_E4_SuperPershing_S1
"germany:Indien_Panzer":
- other:Oth37_T26_E4_SuperPershing_S1
- other:Oth51_FD_24
"china:Ch05_T34_2":
- other:Oth51_FD_24
- other:Oth52_Toxique
"japan:STA_1":
- other:Akawara
- other:Oth30_T54MS
"uk:GB23_Centurion":
- other:Oth30_T54MS
- other:Oth52_Toxique
"usa:Pershing":
- other:Akawara
- other:Oth40_TVP_46_S2
"usa:T69":
- other:Oth37_T26_E4_SuperPershing_S1
- other:Oth52_Toxique
"ussr:T-44":
- other:Oth30_T54MS
- other:Oth37_T26_E4_SuperPershing_S1
#HT
"european:It117_ProgettoCC55mod54":
- other:Oth71_Titan_Strife
- other:Oth77_Prowler
"european:Cz18_TNH_105_1000":
- other:Oth71_Titan_Strife
- other:Oth77_Prowler
"european:Pl13_53TP_Markowskiego":
- other:Oth71_Titan_Strife
- other:Oth73_Nemini
"european:S18_EMIL_1951E1":
- other:Oth71_Titan_Strife
- other:Oth73_Nemini
"france:AMX_50_100":
- other:Oth71_Titan_Strife
- other:Oth73_Nemini
"germany:VK4502A":
- other:Oth45_Sandstriker
- other:Oth77_Prowler
"germany:G115_VK10001P":
- other:Oth45_Sandstriker
- other:Oth77_Prowler
"germany:PzVIB_Tiger_II":
- other:Oth45_Sandstriker
- other:Oth71_Titan_Strife
"china:Ch50_BZ_166":
- other:Oth45_Sandstriker
- other:Oth71_Titan_Strife
"china:Ch11_110":
- other:Oth73_Nemini
- other:Oth77_Prowler
"japan:J27_Chi_Se":
- other:Oth73_Nemini
- other:Oth77_Prowler
"uk:GB11_Caernarvon":
- other:Oth73_Nemini
- other:Oth77_Prowler
"usa:T32":
- other:Oth45_Sandstriker
- other:Oth73_Nemini
"usa:M-3-Y":
- other:Oth45_Sandstriker
- other:Oth73_Nemini
"ussr:KV4":
- other:Oth45_Sandstriker
- other:Oth73_Nemini
"ussr:IS-3":
- other:Oth45_Sandstriker
- other:Oth73_Nemini
#TD
"china:Ch36_WZ-111-1G_FT":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"european:It18_Semovente_mod_64":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"germany:RhB_Waffentrager":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"germany:JagdPantherII":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"germany:Ferdinand":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"japan:J22_Ho_Ri_type96":
- other:Oth44_Charioteer_T
- other:Oth69_Souleater
"uk:GB72_AT15":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
"uk:GB80_Charioteer":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
"usa:T28_Prototype":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
"usa:T28":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
"ussr:SU-101":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
"ussr:ISU-152":
- other:Oth44_Charioteer_T
- other:Oth67_FV215b_183ANN_S4
#九级
#MT
"european:It12_Prototipo_Standard_B":
- other:Oth11_T-55A
- other:Oth75_Braniaq_DM5
"european:Cz02_T50":
- other:Oth11_T-55A
- other:Oth75_Braniaq_DM5
"european:Pl22_CS_59":
- other:Oth11_T-55A
- other:Oth75_Braniaq_DM5
"france:F120_Project_Louis":
- other:Oth11_T-55A
- other:Oth75_Braniaq_DM5
"germany:E-50":
- other:Oth41_Centurion_Mk3_S2
- other:Oth75_Braniaq_DM5
"germany:Pro_Ag_A":
- other:Oth41_Centurion_Mk3_S2
- other:Oth75_Braniaq_DM5
"china:Ch18_WZ-120":
- other:Oth41_Centurion_Mk3_S2
- other:Oth75_Braniaq_DM5
"japan:Type_61":
- other:Oth41_Centurion_Mk3_S2
- other:Oth75_Braniaq_DM5
"uk:GB24_Centurion_Mk3":
- other:Oth11_T-55A
- other:Oth41_Centurion_Mk3_S2
"usa:M46_Patton":
- other:Oth11_T-55A
- other:Oth41_Centurion_Mk3_S2
"usa:T54E1":
- other:Oth11_T-55A
- other:Oth41_Centurion_Mk3_S2
"ussr:T-54":
- other:Oth11_T-55A
- other:Oth41_Centurion_Mk3_S2
#HT
"european:It119_ProgettoC50mod66":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth76_Destiny
"european:Cz16_TNH_T_vz51":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth76_Destiny
"european:Pl05_50TP_Tyszkiewicza":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth76_Destiny
"european:S17_EMIL_1952E2":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth48_EMIL_1951E1_S3
"france:AMX_50_120":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth48_EMIL_1951E1_S3
"germany:VK4502P":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth48_EMIL_1951E1_S3
"germany:G110_Mauschen":
- other:Oth48_EMIL_1951E1_S3
- other:Oth76_Destiny
"germany:E-75":
- other:Oth48_EMIL_1951E1_S3
- other:Oth76_Destiny
"china:Ch49_BZ_68":
- other:Oth48_EMIL_1951E1_S3
- other:Oth76_Destiny
"china:Ch12_111_1_2_3":
- other:Oth48_EMIL_1951E1_S3
- other:Oth68_KV2ANN_S4
"japan:J26_Type_68":
- other:Oth48_EMIL_1951E1_S3
- other:Oth68_KV2ANN_S4
"uk:GB12_Conqueror":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth68_KV2ANN_S4
"usa:M-5-Y":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth68_KV2ANN_S4
"usa:M103":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth68_KV2ANN_S4
"ussr:IS8":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth68_KV2ANN_S4
"ussr:ST_I":
- other:Oth38_50TP_Tyszkiewicza_S1
- other:Oth68_KV2ANN_S4
#TD
"european:It19_Controcarro_1MK2_Ciclope":
- other:Oth74_Argonaut
"france:AMX50_Foch":
- other:Oth74_Argonaut
"germany:Waffentrager_IV":
- other:Oth74_Argonaut
"germany:JagdTiger":
- other:Oth74_Argonaut
"china:Ch37_WZ-111G_FT":
- other:Oth74_Argonaut
"japan:J21_Ho_Ri:":
- other:Oth74_Argonaut
"uk:GB32_Tortoise":
- other:Oth74_Argonaut
"uk:GB81_FV4004":
- other:Oth74_Argonaut
"usa:T30":
- other:Oth74_Argonaut
"usa:T95":
- other:Oth74_Argonaut
"ussr:SU122_54":
- other:Oth74_Argonaut
"ussr:Object_704":
- other:Oth74_Argonaut