modules:
    "#vehicle:IS-3":
        position: [4, 2]
    "#vehicleGun:_100mm_D10T":
        position: [1, 1]
    "#vehicleGun:_122-mm_D-25T_with_a_piston_shutter":
        position: [3, 2]
    "#vehicleGun:_122-mm_D-25T_with_wedges_shutter":
        position: [4, 1]
    "#vehicleTurret:IS-122":
        position: [2, 2]
    "#vehicleTurret:IS-85":
        position: [1, 2]
    "#vehicleEngine:V-2-54IS":
        position: [2, 3]
    "#vehicleEngine:V-2IS":
        position: [1, 3]
    "#vehicleChassis:IS-1":
        position: [1, 4]
    "#vehicleChassis:IS-2M":
        position: [2, 4]