modules:
    "#vehicle:KV-3":
        position: [4, 1]
    "#vehicle:IS":
        position: [4, 2]
    "#vehicleGun:_76mm_S-54":
        position: [1, 1]
    "#vehicleGun:_122-mm_D-25T_with_a_piston_shutter":
        position: [3, 1]
    "#vehicleGun:_85mm_D-5T":
        position: [3, 2]
    "#vehicleTurret:KV1S_mod_42":
        position: [1, 2]
    "#vehicleTurret:KV1S_mod_43":
        position: [2, 1]
    "#vehicleEngine:V-2K":
        position: [1, 3]
    "#vehicleEngine:V-2IS":
        position: [2, 3]
    "#vehicleChassis:KV-1s":
        position: [1, 4]
    "#vehicleChassis:KV-1s_bis":
        position: [2, 4]