modules:
    "#vehicle:KV4":
        position: [2, 1]
    "#vehicleGun:_107mm_ZiS-6":
        position: [1, 1]
    "#vehicleGun:_122-mm_D-25T_with_a_piston_shutter":
        position: [3, 2]
    "#vehicleGun:_100mm_D10T":
        position: [3, 3]
    "#vehicleGun:_122-mm_D-25T_with_wedges_shutter":
        position: [4, 2]
    "#vehicleTurret:KV-220_mod":
        position: [1, 2]
    "#vehicleTurret:KV-3":
        position: [2, 2]
    "#vehicleEngine:V-5":
        position: [1, 3]
    "#vehicleEngine:V-2SN":
        position: [2, 3]
    "#vehicleChassis:KV-3":
        position: [1, 4]
    "#vehicleChassis:KV-3bis":
        position: [2, 4]