modules:
    "#vehicle:KV-3":
        position: [3, 2]
    "#vehicleGun:_122mm_cannon_U-11":
        position: [1, 1]
    "#vehicleGun:_152mm_M-10":
        position: [2, 1]
    "#vehicleGun:_107mm_ZiS-6":
        position: [2, 2]
    "#vehicleTurret:Turret_1_KV2":
        position: [1, 3]
    "#vehicleTurret:Turret_2_KV2":
        position: [2, 3]
    "#vehicleEngine:M-17F":
        position: [1, 4]
    "#vehicleEngine:V-2K":
        position: [2, 4]
    "#vehicleEngine:V-5":
        position: [3, 4]
    "#vehicleChassis:Chassis_KV2_1":
        position: [1, 5]
    "#vehicleChassis:Chassis_KV2_2":
        position: [2, 5]