modules:
    "#vehicle:SU122_54":
        position: [3, 2]
    "#vehicleGun:_100mm_D10S_obr_44":
        position: [1, 1]
    "#vehicleGun:_100mm_D54S":
        position: [2, 1]
    "#vehicleGun:_122mm_D-25C_mod1944":
        position: [2, 2]
    "#vehicleGun:_122mm_M62-T2S":
        position: [3, 1]
    "#vehicleEngine:V-2-44":
        position: [1, 3]
    "#vehicleEngine:V-2-54":
        position: [2, 3]
    "#vehicleEngine:V-54-6":
        position: [3, 3]
    "#vehicleChassis:Chassis_SU-101":
        position: [1, 4]
    "#vehicleChassis:Chassis_SU-101_2":
        position: [2, 4]