modules:
    "#vehicle:T-54":
        position: [3, 4]
    "#vehicleGun:_85mm_D5T-85BM":
        position: [1, 1]
    "#vehicleGun:_122mm_D-25-44":
        position: [3, 1]
    "#vehicleGun:_100mm_D10T":
        position: [3, 2]
    "#vehicleGun:_100mm_LB-1":
        position: [4, 2]
    "#vehicleTurret:T-44":
        position: [1, 2]
    "#vehicleTurret:T-44-100":
        position: [2, 2]
    "#vehicleEngine:V-2-44":
        position: [1, 3]
    "#vehicleEngine:V-2-54":
        position: [2, 3]
    "#vehicleEngine:V-54-6":
        position: [3, 3]
    "#vehicleChassis:T-44":
        position: [1, 4]
    "#vehicleChassis:T-44Bis":
        position: [2, 4]