modules:
    "#vehicle:T62A":
        position: [5, 1]
    "#vehicle:Object_140":
        position: [5, 2]
    "#vehicleGun:_100mm_D10T_obr_45":
        position: [1, 1]
    "#vehicleGun:_100mm_LB-1":
        position: [2, 1]
    "#vehicleGun:_100mm_D54_obr_45":
        position: [4, 1]
    "#vehicleGun:_100mm_D-10T2S":
        position: [4, 2]
    "#vehicleTurret:Turret_1_T-54_2":
        position: [1, 2]
    "#vehicleTurret:Turret_2_T-54_2":
        position: [3, 1]
    "#vehicleEngine:V-2-54":
        position: [1, 3]
    "#vehicleEngine:V-55U":
        position: [2, 3]
    "#vehicleChassis:Chassis_T-54_2":
        position: [1, 4]
    "#vehicleChassis:Chassis_T-54_3":
        position: [2, 4]