Header:
    version: "23"
ImportedPackages:
- "~res:/UI/Screens/Fonts.yaml"
- "~res:/UI/Screens/Lobby/Chat/ChatMessageStyle.yaml"
StyleSheets:
-   selector: ".chat-background"
    properties:
        bg-color: [0.200000, 0.274510, 0.321569, 0.705882]
Controls:
-   class: "UIControl"
    name: "ChatCell"
    size: [466.000000, 50.000000]
    components:
        StyleSheet:
            inheritsStylesFromParent: true
            styles: "~res:/UI/Screens/Lobby/Training/TrainingChatCell.yaml"
    children:
    -   class: "UIControl"
        name: "Bg"
        components:
            Background:
                usePostProcessedSprite: true
            UIPostProcessTextureComponent0:
                materialPath: "~res:/Materials.custom/2d.Textured.Blur.material"
                needClearAlphaAfterRender: true
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            UIPostProcessTextureComponent1:
                materialPath: "~res:/Materials.custom/2d.Textured.HBlur.material"
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            UIPostProcessTextureComponent2:
                materialPath: "~res:/Materials.custom/2d.Textured.UpscaleClamp.material"
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            Anchor:
                leftAnchorEnabled: true
                rightAnchorEnabled: true
                topAnchorEnabled: true
                bottomAnchorEnabled: true
                bottomAnchor: 1.000000
    -   class: "UIStaticText"
        name: "fromName"
        position: [10.000000, 12.000000]
        size: [90.000000, 24.000000]
        noInput: true
        classes: "header4 textColor=chat-nick-text-color"
        components:
            Anchor:
                leftAnchorEnabled: true
                leftAnchor: 10.000000
                topAnchorEnabled: true
                topAnchor: 12.000000
            UITextComponent:
                text: "wot188"
                colorInheritType: "COLOR_IGNORE_PARENT"
                fitting: "FITTING_POINTS"
                align: ["LEFT", "TOP"]
                useRtlAlign: "DONT_USE"
    -   class: "UIStaticText"
        name: "msgText"
        position: [105.000000, 12.000000]
        size: [288.000000, 23.000000]
        noInput: true
        classes: "text2 textColor=chat-msg-text-color"
        components:
            UITextComponent:
                text: "test"
                colorInheritType: "COLOR_IGNORE_PARENT"
                multiline: "MULTILINE_ENABLED"
                align: ["LEFT", "TOP"]
                useRtlAlign: "DONT_USE"
            StyleSheet:
                inheritsStylesFromParent: true
                styles: "~res:/UI/Screens/Fonts.yaml"
    -   class: "UIStaticText"
        name: "timeText"
        position: [406.000000, 13.000000]
        size: [50.000000, 24.000000]
        noInput: true
        classes: "text2 textColor=chat-date-text-color"
        components:
            Anchor:
                rightAnchorEnabled: true
                rightAnchor: 10.000000
                topAnchorEnabled: true
                topAnchor: 13.000000
            UITextComponent:
                text: "18:20"
                colorInheritType: "COLOR_IGNORE_PARENT"
                fitting: "FITTING_REDUCE"
                align: ["RIGHT", "TOP"]
                useRtlAlign: "DONT_USE"
-   class: "UIControl"
    name: "DateSeparatorCell"
    size: [466.000000, 50.000000]
    components:
        StyleSheet:
            inheritsStylesFromParent: true
            styles: "~res:/UI/Screens/Lobby/Training/TrainingChatCell.yaml"
    children:
    -   class: "UIControl"
        name: "Bg"
        components:
            Background:
                usePostProcessedSprite: true
            UIPostProcessTextureComponent0:
                materialPath: "~res:/Materials.custom/2d.Textured.Blur.material"
                needClearAlphaAfterRender: true
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            UIPostProcessTextureComponent1:
                materialPath: "~res:/Materials.custom/2d.Textured.HBlur.material"
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            UIPostProcessTextureComponent2:
                materialPath: "~res:/Materials.custom/2d.Textured.UpscaleClamp.material"
                scale: 0.500000
                useVirtualCoordinateSystem: true
                minFilter: "Linear"
                magFilter: "Linear"
            Anchor:
                leftAnchorEnabled: true
                rightAnchorEnabled: true
                topAnchorEnabled: true
                bottomAnchorEnabled: true
                bottomAnchor: 1.000000
    -   class: "UIStaticText"
        name: "timeText"
        position: [10.000000, 12.000000]
        size: [446.000000, 24.000000]
        noInput: true
        classes: "header4 textColor=chat-nick-text-color"
        components:
            Anchor:
                leftAnchorEnabled: true
                leftAnchor: 10.000000
                rightAnchorEnabled: true
                rightAnchor: 10.000000
                topAnchorEnabled: true
                topAnchor: 12.000000
            UITextComponent:
                text: "wot188"
                colorInheritType: "COLOR_IGNORE_PARENT"
                fitting: "FITTING_POINTS"
                align: ["HCENTER", "TOP"]
                useRtlAlign: "DONT_USE"
