-
    TemplateName: "Textured"
    Flags: [ VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FLATCOLOR, TEXTURE0_SHIFT_ENABLED, TEXTURE0_ANIMATION_SHIFT, TILED_DECAL_MASK, TILED_DECAL_TRANSFORM, TILED_DECAL_ANIMATED_EMISSION, ALBEDO_TRANSFORM, SETUP_LIGHTMAP, ALPHATESTVALUE, ALPHASTEPVALUE, BLEND_BY_ANGLE, SHADOW_RECEIVER, ENVIRONMENT_MAPPING, WIND_ANIMATION, VERTEX_DISPLACEMENT ]
-
    TemplateName: "Textured Lightmap"
    BaseTemplateName: Textured
    Flags: [ IGNORE_LIGHTMAP_ADJUSTMENT ]
-
    TemplateName: "Decal"
    BaseTemplateName: Textured
    Flags: [ LANDSCAPE_SEPARATE_LIGHTMAP_CHANNEL ]
-
    TemplateName: "VertexColor"
    BaseTemplateName: Textured
-
    TemplateName: "Detail"
    BaseTemplateName: Textured
-
    TemplateName: "Detail [Q]"
    BaseTemplateName: Detail
-
    TemplateName: "SpeedTree"
    Flags: [ VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FORCE_2D_MODE, CUT_LEAF, TEXTURE0_SHIFT_ENABLED, TEXTURE0_ANIMATION_SHIFT, SHADOW_RECEIVER, ALPHATESTVALUE, ALPHASTEPVALUE, FLATCOLOR, FLATALBEDO, BILLBOARD_FACE_MAIN_CAMERA ]
-
    TemplateName: "SpeedTree Spherical Lit [Q]"
    BaseTemplateName: SpeedTree
-
    TemplateName: "Standard SpeedTree"
    BaseTemplateName: SpeedTree
-
    TemplateName: "Spherical Lit [Q]"
    Flags: [ MATERIAL_TEXTURE, MATERIAL_DECAL, MATERIAL_DETAIL, ALPHA_MASK, WIND_ANIMATION, TILED_DECAL_MASK, TILED_DECAL_TRANSFORM, TILED_DECAL_ANIMATED_EMISSION, VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FLOWMAP, SHADOW_RECEIVER, TEXTURE0_SHIFT_ENABLED, TEXTURE0_ANIMATION_SHIFT, VERTEX_COLOR, ALBEDO_TRANSFORM, FORCE_2D_MODE, FLATCOLOR, FLATALBEDO ]
-
    TemplateName: "BlinnPhong [Q]"
    Flags: [ ALLOW_POINT_LIGHTS, NORMALIZED_BLINN_PHONG, ALPHA_MASK, VERTEX_COLOR, TILED_DECAL_MASK, TILED_DECAL_TRANSFORM, TILED_DECAL_ANIMATED_EMISSION, MATERIAL_DECAL, ALPHA_MASK, MATERIAL_DETAIL, SHADOW_RECEIVER, ENVIRONMENT_MAPPING, ENVIRONMENT_MAPPING_NORMALMAP, DISTANCE_ATTENUATION, TEXTURE0_SHIFT_ENABLED, TEXTURE0_ANIMATION_SHIFT, VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FORCE_2D_MODE, FLATCOLOR, FLATALBEDO, VERTEX_DISPLACEMENT ]
-
    TemplateName: "Skyobject"
    Flags: [ FORCE_2D_MODE, FLATCOLOR ]
-
    TemplateName: "Landscape [Q]"
    Flags: [ VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, IGNORE_LIGHTMAP_ADJUSTMENT, LANDSCAPE_USE_RELAXMAP, LANDSCAPE_HEIGHT_BLEND, LANDSCAPE_SEPARATE_LIGHTMAP_CHANNEL, LANDSCAPE_SCALED_TILES_NON_PBR ]
-
    TemplateName: "Water [Q]"
    Flags: [ SPECULAR, VERTEX_FOG, SHADOW_RECEIVER, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR ]
-
    TemplateName: "Standard"
    Flags: [ ALLOW_POINT_LIGHTS, NORMALIZED_BLINN_PHONG, ALPHA_MASK, VERTEX_COLOR, VERTEX_DISTORTION, TILED_DECAL_MASK, TILED_DECAL_TRANSFORM, TILED_DECAL_ANIMATED_EMISSION, TILED_DECAL_BLEND_NORMAL, TILED_DECAL_OVERRIDE_ROUGHNESS_METALLIC, ALPHA_MASK, SHADOW_RECEIVER, ENVIRONMENT_MAPPING, ENVIRONMENT_MAPPING_NORMALMAP, DISTANCE_ATTENUATION, TEXTURE0_SHIFT_ENABLED, TEXTURE0_ANIMATION_SHIFT, VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FORCE_2D_MODE, FLATCOLOR, FLATALBEDO, AMBIENT_ATTENUATION_BOX, DIRT_COVERAGE, WETNESS_SIMPLIFIED, MATERIAL_DECAL, MATERIAL_DETAIL, MATERIAL_LIGHTMAP, PBR_DECAL, PBR_DETAIL, PBR_LIGHTMAP, EMISSIVE_COLOR, EMISSIVE_ALBEDO, TILED_DECAL_EMISSIVE_ALBEDO, VERTEX_DISPLACEMENT ]
-
    TemplateName: "Standard Lightmap"
    Flags: [ ALLOW_POINT_LIGHTS, ALPHA_MASK, VERTEX_COLOR, VERTEX_DISTORTION, ALPHA_MASK, SHADOW_RECEIVER, EMISSIVE_COLOR, ENVIRONMENT_MAPPING, ENVIRONMENT_MAPPING_NORMALMAP, DISTANCE_ATTENUATION, VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, FORCE_2D_MODE, FLATCOLOR, FLATALBEDO, MATERIAL_DECAL, MATERIAL_DETAIL, MATERIAL_LIGHTMAP, PBR_DECAL, PBR_DETAIL, PBR_LIGHTMAP, WIND_ANIMATION, IGNORE_LIGHTMAP_ADJUSTMENT, LANDSCAPE_SEPARATE_LIGHTMAP_CHANNEL, VERTEX_DISPLACEMENT ]
-
    TemplateName: "Standard Landscape"
    Flags: [ VERTEX_FOG, FOG_LINEAR, FOG_ATMOSPHERE, FOG_HALFSPACE, FOG_HALFSPACE_LINEAR, LANDSCAPE_USE_RELAXMAP, LANDSCAPE_HEIGHT_BLEND, LANDSCAPE_SEPARATE_LIGHTMAP_CHANNEL, LANDSCAPE_HAS_METALLIC_AND_EMISSION, LANDSCAPE_SCALED_TILES_NON_PBR ]
-
    TemplateName: "Simple Color"
    Flags: [ FORCE_2D_MODE, FLATCOLOR ]
