modules:
    "#vehicle:Cz29_Skoda_P-JS":
        position: [3, 4]
    "#vehicle:Cz08_T-25":
        position: [3, 5]
    "#vehicle:Pl10_40TP_Habicha":
        position: [4, 1]
    "#vehicle:S07_Strv_74":
        position: [4, 2]
    "#vehicle:It10_P43_bis":
        position: [4, 3]
    "#vehicleGun:_75mm_kan_m_41_strv":
        position: [1, 2]
    "#vehicleGun:_75mm_kan_m_43_strv":
        position: [3, 2]
    "#vehicleTurret:Turret_1_S02_Strv_M42":
        position: [1, 3]
    "#vehicleTurret:Turret_2_S02_Strv_M42":
        position: [2, 2]
    "#vehicleEngine:_2_st_Scania_Vabis_L_603_1":
        position: [1, 4]
    "#vehicleEngine:Volvo_A8B":
        position: [2, 4]
    "#vehicleChassis:Chassis_S02_Strv_M42":
        position: [1, 5]
    "#vehicleChassis:Chassis_S02_Strv_M42_2":
        position: [2, 5]