modules:
    "#vehicle:It15_Semovente_M41":
        position: [4, 1]
    "#vehicle:S02_StrvM42":
        position: [3, 3]
    "#vehicle:Pl17_DS_PZlnz":
        position: [3, 4]
    "#vehicleTurret:Turret_1_S04_Lago_I":
        position: [1, 2]
    "#vehicleTurret:Turret_2_S04_Lago_I":
        position: [2, 1]
    "#vehicleGun:_57mm_pvkan_m_43":
        position: [1, 1]
    "#vehicleGun:_75mm_kan_m_41_strv_A":
        position: [3, 1]
    "#vehicleEngine:_2_st_Scania_Vabis_1664":
        position: [1, 3]
    "#vehicleEngine:_2_st_Scania_Vabis_L_603_1":
        position: [2, 3]
    "#vehicleChassis:Chassis_S04_Lago_I":
        position: [1, 4]
    "#vehicleChassis:Chassis_S04_Lago_I_2":
        position: [2, 4]