modules:
    "#vehicle:Indien_Panzer":
        position: [5, 1]
    "#vehicle:G103_RU_251":
        position: [5, 2]
    "#vehicleGun:_90mm_D921_F1":
        position: [1, 1]
    "#vehicleGun:_90mm_Mecar":
        position: [3, 2]
    "#vehicleGun:_90mm_Mecar_mit_Mehrladeeinrichtung":
        position: [4, 2]
    "#vehicleTurret:Turret_1_G113_SP_I_C":
        position: [1, 2]
    "#vehicleTurret:Turret_2_G113_SP_I_C":
        position: [2, 2]
    "#vehicleEngine:Hotchkiss_6_Zyl_Benzin_154_PS":
        position: [1, 3]
    "#vehicleEngine:Hotchkiss_6_Zyl_Benzin_164_PS":
        position: [2, 3]
    "#vehicleEngine:Hotchkiss_6_Zyl_Benzin_195_PS":
        position: [3, 3]
    "#vehicleChassis:Chassis_G113_SP_I_C":
        position: [1, 4]
    "#vehicleChassis:Chassis_G113_SP_I_C_2":
        position: [2, 4]