modules:
    "#vehicle:JagdPanther":
        position: [2, 2]
    "#vehicleGun:_75mm_PaK_39_L48":
        position: [1, 1]
    "#vehicleGun:_75mm_StuK42_L70":
        position: [2, 1]
    "#vehicleGun:_88mm_PaK_36_L56":
        position: [3, 1]
    "#vehicleEngine:Maybach_HL_108TR":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_120_TR":
        position: [2, 3]
    "#vehicleEngine:Maybach_HL_120_TRM":
        position: [3, 3]
    "#vehicleChassis:JagdPzIV_Ausf_1940":
        position: [1, 4]
    "#vehicleChassis:JagdPzIV_Ausf_1943":
        position: [2, 4]