modules:
    "#vehicle:JagdPzIV":
        position: [2, 2]
    "#vehicle:Nashorn":
        position: [3, 1]
    "#vehicleGun:_75mm_PaK_39_L48":
        position: [1, 1]
    "#vehicleGun:_75mm_StuK42_L70":
        position: [2, 1]
    "#vehicleEngine:Maybach_HL_108TR":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_120_TRM":
        position: [2, 3]
    "#vehicleChassis:StuGIII_Ausf_1940":
        position: [1, 4]
    "#vehicleChassis:StuGIII_Ausf_1943":
        position: [2, 4]