modules:
    "#vehicle:G113_SP_I_C":
        position: [3, 3]
    "#vehicleGun:_75mm_KwK_40_L48":
        position: [1, 1]
    "#vehicleGun:_105mm_StuH42_L28Pz":
        position: [3, 1]
    "#vehicleGun:_75mm_KwK41_L58_conic":
        position: [3, 2]
    "#vehicleTurret:Turret_1_VK2801":
        position: [1, 2]
    "#vehicleTurret:Turret_2_VK2801":
        position: [2, 1]
    "#vehicleEngine:Maybach_HL_157P":
        position: [1, 3]
    "#vehicleEngine:Maybach_HL_210P30":
        position: [2, 3]
    "#vehicleChassis:Chassis_VK2801":
        position: [1, 4]
    "#vehicleChassis:Chassis_VK2801_2":
        position: [2, 4]