modules:
    "#vehicle:GB10_Black_Prince":
        position: [4, 2]
    "#vehicleGun:QF_6_pounder_Mk_V":
        position: [1, 1]
    "#vehicleGun:_75mm_Gun_Vickers_HV":
        position: [2, 1]
    "#vehicleGun:OQF_77mm_Gun_MkII":
        position: [3, 2]
    "#vehicleTurret:Turret_1_GB09_Churchill_VII":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB09_Churchill_VII":
        position: [2, 2]
    "#vehicleEngine:Meadows_DAV":
        position: [1, 3]
    "#vehicleEngine:Vauxhall_Bedford_Twin_Six":
        position: [2, 3]
    "#vehicleChassis:Chassis_GB09_Churchill_VII":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB09_Churchill_VII_2":
        position: [2, 4]