modules:
    "#vehicle:GB21_Cromwell":
        position: [4, 1]
    "#vehicle:GB19_Sherman_Firefly":
        position: [4, 2]
    "#vehicleGun:QF_6_pounder_Mk_III":
        position: [1, 1]
    "#vehicleGun:QF_6_pounder_Mk_V":
        position: [3, 1]
    "#vehicleTurret:Turret_1_GB20_Crusader":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB20_Crusader":
        position: [2, 1]
    "#vehicleEngine:Nuffield_liberty_MKIV":
        position: [1, 3]
    "#vehicleEngine:Nuffield_liberty_MKV":
        position: [2, 3]
    "#vehicleChassis:Chassis_GB20_Crusader":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB20_Crusader_2":
        position: [2, 4]