modules:
    "#vehicle:GB23_Centurion":
        position: [4, 2]
    "#vehicle:GB_FV301":
        position: [3, 3]
    "#vehicleGun:_75mm_Gun_Vickers_HV":
        position: [1, 1]
    "#vehicleGun:OQF_77mm_Gun_MkIIB":
        position: [3, 1]
    "#vehicleGun:OQF_77mm_Gun_MkII_CM":
        position: [3, 2]
    "#vehicleTurret:Turret_1_GB22_Comet":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB22_Comet":
        position: [2, 2]
    "#vehicleEngine:Rolls_Royse_Meteor_CR":
        position: [1, 3]
    "#vehicleEngine:Rolls_Royse_Meteor_MkIV_CR":
        position: [2, 3]
    "#vehicleChassis:Chassis_GB22_Comet":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB22_Comet_2":
        position: [2, 4]