modules:
    "#vehicle:GB24_Centurion_Mk3":
        position: [4, 2]
    "#vehicleGun:OQF_77mm_Gun_MkII":
        position: [1, 1]
    "#vehicleGun:OQF_17pdr_Gun_Mk_VII":
        position: [2, 1]
    "#vehicleGun:_20pdr_Gun_Type_BM":
        position: [3, 1]
    "#vehicleGun:_20pdr_Gun_Type_AF":
        position: [3, 2]
    "#vehicleTurret:Turret_1_GB23_Centurion":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB23_Centurion":
        position: [2, 2]
    "#vehicleEngine:Rolls_Royse_Meteor":
        position: [1, 3]
    "#vehicleEngine:Rolls_Royse_Meteor_MkIV":
        position: [2, 3]
    "#vehicleEngine:Rolls_Royse_Meteor_MkIVCV":
        position: [3, 3]
    "#vehicleChassis:Chassis_GB23_Centurion":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB23_Centurion_2":
        position: [2, 4]