modules:
    "#vehicle:GB70_FV4202_105":
        position: [5, 2]
    "#vehicleGun:_20pdr_Gun_Type_AF":
        position: [1, 1]
    "#vehicleGun:_20pdr_Gun_Type_B":
        position: [2, 1]
    "#vehicleGun:_105mm_Gun_L7K":
        position: [4, 1]
    "#vehicleGun:_105mm_Gun_L7BK":
        position: [5, 1]
    "#vehicleTurret:Turret_1_GB24_Centurion_Mk3":
        position: [1, 2]
    "#vehicleTurret:Turret_2_GB24_Centurion_Mk3":
        position: [3, 1]
    "#vehicleEngine:Rolls_Royse_Meteor_MkIV":
        position: [1, 3]
    "#vehicleEngine:Rolls_Royse_Meteor_MkIVCV":
        position: [2, 3]
    "#vehicleEngine:Rolls_Royce_Griffon":
        position: [3, 3]
    "#vehicleChassis:Chassis_GB24_Centurion_Mk3":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB24_Centurion_Mk3_2":
        position: [2, 4]