modules:
    "#vehicle:GB32_Tortoise":
        position: [3, 2]
    "#vehicleGun:_17pdr_OQF_AT_Heavy":
        position: [1, 1]
    "#vehicleGun:_32-pounder_AT_Gun_OQF":
        position: [2, 2]
    "#vehicleGun:_20pdr_AT_Gun_Type_A":
        position: [2, 1]
    "#vehicleGun:_20pdr_AT_Gun_Type_B":
        position: [3, 1]
    "#vehicleEngine:Ford_GAA":
        position: [1, 3]
    "#vehicleEngine:Rolls_Royse_Meteor":
        position: [2, 3]
    "#vehicleEngine:Rolls_Royse_Meteor_MkV":
        position: [3, 3]
    "#vehicleChassis:Chassis_GB72_AT15":
        position: [1, 4]
    "#vehicleChassis:Chassis_GB72_AT15_2":
        position: [2, 4]