modules:
    "#vehicle:GB72_AT15":
        position: [4, 2]
    "#vehicleGun:QF_6_pounder_Mk_V_AT":
        position: [1, 1]
    "#vehicleGun:OQF_77mm_AT_Gun_MkII":
        position: [2, 1]
    "#vehicleGun:_17pdr_OQF_AT_Heavy":
        position: [3, 1]
    "#vehicleGun:_20pdr_AT_Gun_Type_A":
        position: [4, 1]
    "#vehicleEngine:Nuffield_liberty_MKIV":
        position: [1, 2]
    "#vehicleEngine:Nuffield_liberty_MKV":
        position: [2, 2]
    "#vehicleEngine:Ford_GAA":
        position: [3, 2]
    "#vehicleChassis:Chassis_GB75_AT7":
        position: [1, 3]
    "#vehicleChassis:Chassis_GB75_AT7_2":
        position: [2, 3]