modules:
    "#vehicle:Ch18_WZ-120":
        position: [6, 1]
    "#vehicleGun:_85mm_S-53":
        position: [1, 1]
    "#vehicleGun:_85mm_Tip_56-85JT":
        position: [2, 1]
    "#vehicleGun:_100mm_44-100JT":
        position: [4, 1]
    "#vehicleGun:_100mm_59-100T":
        position: [5, 1]
    "#vehicleGun:_122-mm_37-122JT":
        position: [5, 2]
    "#vehicleTurret:Turret_1_Ch05_T34_2":
        position: [1, 2]
    "#vehicleTurret:Turret_2_Ch05_T34_2":
        position: [3, 1]
    "#vehicleEngine:_Type_102S1":
        position: [1, 3]
    "#vehicleEngine:_12150L":
        position: [2, 3]
    "#vehicleEngine:_12150LS":
        position: [3, 3]
    "#vehicleChassis:Chassis_Ch05_T34_2":
        position: [1, 4]
    "#vehicleChassis:Chassis_Ch05_T34_2_2":
        position: [2, 4]