modules:
    "#vehicle:M-6-Y":
        position: [3, 1]
    "#vehicleGun:_105mm_Gun_T140":
        position: [1, 1]
    "#vehicleGun:_105mm_Gun_T140A":
        position: [2, 1]
    "#vehicleGun:_120mm_Gun_T123E2":
        position: [2, 2]
    "#vehicleTurret:Turret_1_M-5-Y":
        position: [1, 2]
    "#vehicleEngine:AOI-1490A":
        position: [1, 3]
    "#vehicleEngine:GM_X-11":
        position: [2, 3]
    "#vehicleEngine:GM_X-12":
        position: [3, 3]
    "#vehicleChassis:Chassis_M-5-Y_1":
        position: [1, 4]
    "#vehicleChassis:Chassis_M-5-Y_2":
        position: [2, 4]