modules:
    "#vehicle:A100_T49":
        position: [5, 1]
    "#vehicleGun:_76mm_Gun_T91":
        position: [1, 1]
    "#vehicleGun:_76mm_Gun_M32":
        position: [2, 1]
    "#vehicleGun:_76mm_Gun_T91E5":
        position: [2, 2]
    "#vehicleGun:_76mm_Gun_M32_late":
        position: [4, 1]
    "#vehicleTurret:Turret_1_M41_Bulldog":
        position: [1, 2]
    "#vehicleTurret:Turret_2_M41_Bulldog":
        position: [3, 1]
    "#vehicleEngine:Continental_AOS-895-3":
        position: [1, 3]
    "#vehicleEngine:Continental_AOSI-895-5":
        position: [2, 3]
    "#vehicleChassis:Chassis_M41_Bulldog":
        position: [1, 4]
    "#vehicleChassis:Chassis_M41_Bulldog_2":
        position: [2, 4]