modules:
    "#vehicle:M4A3E8_Sherman":
        position: [4, 1]
    "#vehicle:A94_T37":
        position: [4, 2]
    "#vehicle:M24_Chaffee":
        position: [4, 3]
    "#vehicleGun:_75mm_Gun_M3_L37":
        position: [1, 1]
    "#vehicleGun:_76mm_Gun_M1A1":
        position: [3, 1]
    "#vehicleTurret:D51072":
        position: [2, 1]
    "#vehicleTurret:D51066":
        position: [1, 2]
    "#vehicleEngine:Wright_Continental_R-975EC2":
        position: [1, 3]
    "#vehicleEngine:Wright_Continental_R-975C1":
        position: [2, 3]
    "#vehicleEngine:Wright_Continental_R-975C4":
        position: [3, 3]
    "#vehicleChassis:T41":
        position: [1, 4]
    "#vehicleChassis:T42":
        position: [2, 4]
