modules:
    "#vehicle:T32":
        position: [3, 2]
    "#vehicleGun:_90mm_Gun_M3":
        position: [1, 1]
    "#vehicleGun:_105mm_Gun_T5E1":
        position: [2, 1]
    "#vehicleTurret:T123":
        position: [1, 2]
    "#vehicleTurret:T136":
        position: [2, 2]
    "#vehicleEngine:Ford_GAC":
        position: [1, 3]
    "#vehicleEngine:GMC_Allison_V1710-E32":
        position: [2, 3]
    "#vehicleEngine:Continental_AV-1790-3":
        position: [3, 3]
    "#vehicleChassis:T84E1":
        position: [1, 4]
    "#vehicleChassis:T84E3":
        position: [2, 4]