modules:
    "#vehicle:T110E4":
        position: [3, 2]
    "#vehicleGun:_105mm_AT_Gun_T5E1":
        position: [1, 1]
    "#vehicleGun:_120mm_AT_Gun_T53":
        position: [2, 1]
    "#vehicleGun:_155mm_AT_Gun_T7M1":
        position: [3, 1]
    "#vehicleTurret:T30D1":
        position: [1, 2]
    "#vehicleEngine:Continental_AV-1790-3M":
        position: [1, 3]
    "#vehicleEngine:Continental_AV-1790-5":
        position: [2, 3]
    "#vehicleChassis:T80E3A":
        position: [1, 4]
    "#vehicleChassis:T84E38":
        position: [2, 4]