modules:
    "#vehicle:T-26":
        position: [4, 1]
    "#vehicle:BT-2":
        position: [4, 3]
    "#vehicleGun:_37mm_Gochkins":
        position: [1, 1]
    "#vehicleGun:_45mm_mod_1932":
        position: [3, 1]
    "#vehicleGun:_23mm_VJA":
        position: [3, 2]
    "#vehicleTurret:T-18_Standart":
        position: [1, 2]
    "#vehicleTurret:T-18_mod":
        position: [2, 2]
    "#vehicleEngine:AMO-3":
        position: [1, 3]
    "#vehicleChassis:T-18Bis":
        position: [1, 4]