modules:
    "#vehicle:R107_LTB":
        position: [4, 1]
    "#vehicle:R131_LTG":
        position: [4, 3]
    "#vehicleGun:_57mm_ZiS-4":
        position: [1, 1]
    "#vehicleGun:_76mm_S-54":
        position: [3, 1]
    "#vehicleGun:_45mm_automatic_S-20":
        position: [4, 2]
    "#vehicleGun:_57mm_automatic_S-10":
        position: [5, 2]
    "#vehicleTurret:Turret_1_R101_MT25":
        position: [1, 2]
    "#vehicleTurret:Turret_2_R101_MT25":
        position: [2, 1]
    "#vehicleEngine:V-2K":
        position: [1, 3]
    "#vehicleEngine:V-2IS_R":
        position: [2, 3]
    "#vehicleEngine:V-16":
        position: [3, 3]
    "#vehicleChassis:Chassis_R101_MT25":
        position: [1, 4]
    "#vehicleChassis:Chassis_R101_MT25_2":
        position: [2, 4]