modules:
    "#vehicle:T-54":
        position: [3, 2]
    "#vehicle:R_Object_84":
        position: [3, 3]
    "#vehicleGun:_100mm_D10T":
        position: [1, 1]
    "#vehicleGun:_100mm_D10T_obr_45":
        position: [2, 1]
    "#vehicleTurret:Turret_2_R109_T54S":
        position: [1, 2]
    "#vehicleEngine:V-54":
        position: [1, 3]
    "#vehicleEngine:V-55U":
        position: [2, 3]
    "#vehicleChassis:Chassis_R109_T54S":
        position: [1, 4]
    "#vehicleChassis:Chassis_R109_T54S_2":
        position: [2, 4]