modules:
    "#vehicle:SU100M1":
        position: [3, 1]
    "#vehicle:SU-152":
        position: [4, 2]
    "#vehicleGun:_85mm_D-5S":
        position: [1, 1]
    "#vehicleGun:_85mm_D5S-85BM":
        position: [2, 1]
    "#vehicleGun:_100mm_D10S":
        position: [2, 2]
    "#vehicleGun:_122-mm_D-25S_with_a_piston_shutter":
        position: [3, 2]
    "#vehicleEngine:V-2-34":
        position: [1, 3]
    "#vehicleEngine:V-2-34M":
        position: [2, 3]
    "#vehicleChassis:SU-100_mod_1944":
        position: [1, 4]
    "#vehicleChassis:SU-100_mod_1945":
        position: [2, 4]