modules:
    "#vehicle:SU-101":
        position: [2, 2]
    "#vehicleGun:_100mm_D10S_obr_44":
        position: [1, 1]
    "#vehicleGun:_100mm_LB-1S":
        position: [2, 1]
    "#vehicleGun:_100mm_D54S":
        position: [3, 1]
    "#vehicleEngine:V-2-34":
        position: [1, 3]
    "#vehicleEngine:V-2-34M":
        position: [2, 3]
    "#vehicleEngine:V-54K":
        position: [3, 3]
    "#vehicleChassis:Chassis_SU100M1":
        position: [1, 4]
    "#vehicleChassis:Chassis_SU100M1_2":
        position: [2, 4]