modules:
    "#vehicle:It116_Carro_d_assalto_P88":
        position: [4, 2]
    "#vehicle:It09_P43_ter":
        position: [4, 3]
    "#vehicleGun:_75mm_Cannone_da_50_Skoda":
        position: [1, 2]
    "#vehicleGun:_90mm_Cannone_da_42":
        position: [3, 2]
    "#vehicleTurret:Turret_1_It10_P43_bis":
        position: [1, 3]
    "#vehicleTurret:Turret_2_It10_P43_bis":
        position: [2, 2]
    "#vehicleEngine:SPA_242":
        position: [1, 4]
    "#vehicleEngine:SPA_343":
        position: [2, 4]
    "#vehicleEngine:V_2_34_modificato":
        position: [3, 4]
    "#vehicleChassis:Chassis_It10_P43_bis":
        position: [1, 5]
    "#vehicleChassis:Chassis_It10_P43_bis_2":
        position: [2, 5]